# Generated by Django 4.2.11 on 2024-11-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='name',
            field=models.CharField(default='ok', max_length=100),
        ),
    ]
