# Generated by Django 4.2.11 on 2024-11-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_rate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
