# Generated by Django 4.2.11 on 2024-11-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_alter_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='message',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
