# Generated by Django 4.2.11 on 2024-11-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_alter_rate_message_alter_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(max_length=100),
        ),
    ]
